services:
  # Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: academy-postgres
    environment:
      POSTGRES_DB: academy
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - academy-network

  # Keycloak for authentication
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: academy-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/academy
      KC_DB_USERNAME: academy
      KC_DB_PASSWORD: academy123
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - academy-network

  # Backend Quarkus
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: academy-backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/academy
      QUARKUS_DATASOURCE_USERNAME: academy
      QUARKUS_DATASOURCE_PASSWORD: academy123
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/academy
      QUARKUS_OIDC_CLIENT_ID: academy-backend
      QUARKUS_OIDC_CREDENTIALS_SECRET: secret
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    networks:
      - academy-network

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: academy-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - academy-network

volumes:
  postgres_data:

networks:
  academy-network:
    driver: bridge
